# Generated by Django 5.0.7 on 2024-07-20 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='город')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='температура')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'погода',
                'verbose_name_plural': 'погода',
            },
        ),
    ]
